/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as EditorialStandardsRouteImport } from './routes/editorial-standards'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProRouteImport } from './routes/pro'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SiteMapRouteImport } from './routes/site-map'
import { Route as TakedownRouteImport } from './routes/takedown'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as CreatorsIndexRouteImport } from './routes/creators/index'
import { Route as CreatorsHandleRouteImport } from './routes/creators/$handle'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as LegalSlugRouteImport } from './routes/legal/$slug'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as PromptSlugRouteImport } from './routes/prompt/$slug'
import { Route as PromptsSlugRouteImport } from './routes/prompts/$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable/oauth/consent'
import { Route as BrowsePriceIndexRouteImport } from './routes/browse/$price/index'
import { Route as PromptCategorySlugRouteImport } from './routes/prompt/$category/$slug'
import { Route as BrowsePriceModelIndexRouteImport } from './routes/browse/$price/$model/index'
import { Route as BrowsePriceModelCategoryRouteImport } from './routes/browse/$price/$model/$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialStandardsRoute = EditorialStandardsRouteImport.update({
  id: '/editorial-standards',
  path: '/editorial-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteMapRoute = SiteMapRouteImport.update({
  id: '/site-map',
  path: '/site-map',
  getParentRoute: () => rootRouteImport,
} as any)
const TakedownRoute = TakedownRouteImport.update({
  id: '/takedown',
  path: '/takedown',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsIndexRoute = CreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsHandleRoute = CreatorsHandleRouteImport.update({
  id: '/creators/$handle',
  path: '/creators/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptSlugRoute = PromptSlugRouteImport.update({
  id: '/prompt/$slug',
  path: '/prompt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsSlugRoute = PromptsSlugRouteImport.update({
  id: '/prompts/$slug',
  path: '/prompts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePriceIndexRoute = BrowsePriceIndexRouteImport.update({
  id: '/browse/$price/',
  path: '/browse/$price/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptCategorySlugRoute = PromptCategorySlugRouteImport.update({
  id: '/prompt/$category/$slug',
  path: '/prompt/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePriceModelIndexRoute = BrowsePriceModelIndexRouteImport.update({
  id: '/browse/$price/$model/',
  path: '/browse/$price/$model/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePriceModelCategoryRoute =
  BrowsePriceModelCategoryRouteImport.update({
    id: '/browse/$price/$model/$category',
    path: '/browse/$price/$model/$category',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dmca': typeof DmcaRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/glossary': typeof GlossaryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pro': typeof ProRoute
  '/refunds': typeof RefundsRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site-map': typeof SiteMapRoute
  '/takedown': typeof TakedownRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/trust': typeof TrustRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/browse/': typeof BrowseIndexRoute
  '/creators/': typeof CreatorsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/prompt/$category/$slug': typeof PromptCategorySlugRoute
  '/browse/$price/': typeof BrowsePriceIndexRoute
  '/browse/$price/$model/$category': typeof BrowsePriceModelCategoryRoute
  '/browse/$price/$model/': typeof BrowsePriceModelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dmca': typeof DmcaRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/glossary': typeof GlossaryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pro': typeof ProRoute
  '/refunds': typeof RefundsRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site-map': typeof SiteMapRoute
  '/takedown': typeof TakedownRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/trust': typeof TrustRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/browse': typeof BrowseIndexRoute
  '/creators': typeof CreatorsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/prompt/$category/$slug': typeof PromptCategorySlugRoute
  '/browse/$price': typeof BrowsePriceIndexRoute
  '/browse/$price/$model/$category': typeof BrowsePriceModelCategoryRoute
  '/browse/$price/$model': typeof BrowsePriceModelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dmca': typeof DmcaRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/glossary': typeof GlossaryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pro': typeof ProRoute
  '/refunds': typeof RefundsRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site-map': typeof SiteMapRoute
  '/takedown': typeof TakedownRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/trust': typeof TrustRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/browse/': typeof BrowseIndexRoute
  '/creators/': typeof CreatorsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/prompt/$category/$slug': typeof PromptCategorySlugRoute
  '/browse/$price/': typeof BrowsePriceIndexRoute
  '/browse/$price/$model/$category': typeof BrowsePriceModelCategoryRoute
  '/browse/$price/$model/': typeof BrowsePriceModelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/cookie-policy'
    | '/cookies'
    | '/dashboard'
    | '/disclaimer'
    | '/dmca'
    | '/editorial-standards'
    | '/glossary'
    | '/library'
    | '/login'
    | '/messages'
    | '/privacy'
    | '/privacy-policy'
    | '/pro'
    | '/refunds'
    | '/register'
    | '/saved'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/site-map'
    | '/takedown'
    | '/terms'
    | '/terms-of-service'
    | '/trust'
    | '/category/$slug'
    | '/checkout/return'
    | '/creators/$handle'
    | '/guides/$slug'
    | '/legal/$slug'
    | '/profile/$username'
    | '/profile/edit'
    | '/prompt/$slug'
    | '/prompts/$slug'
    | '/browse/'
    | '/creators/'
    | '/guides/'
    | '/.lovable/oauth/consent'
    | '/prompt/$category/$slug'
    | '/browse/$price/'
    | '/browse/$price/$model/$category'
    | '/browse/$price/$model/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/cookie-policy'
    | '/cookies'
    | '/dashboard'
    | '/disclaimer'
    | '/dmca'
    | '/editorial-standards'
    | '/glossary'
    | '/library'
    | '/login'
    | '/messages'
    | '/privacy'
    | '/privacy-policy'
    | '/pro'
    | '/refunds'
    | '/register'
    | '/saved'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/site-map'
    | '/takedown'
    | '/terms'
    | '/terms-of-service'
    | '/trust'
    | '/category/$slug'
    | '/checkout/return'
    | '/creators/$handle'
    | '/guides/$slug'
    | '/legal/$slug'
    | '/profile/$username'
    | '/profile/edit'
    | '/prompt/$slug'
    | '/prompts/$slug'
    | '/browse'
    | '/creators'
    | '/guides'
    | '/.lovable/oauth/consent'
    | '/prompt/$category/$slug'
    | '/browse/$price'
    | '/browse/$price/$model/$category'
    | '/browse/$price/$model'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/cookie-policy'
    | '/cookies'
    | '/dashboard'
    | '/disclaimer'
    | '/dmca'
    | '/editorial-standards'
    | '/glossary'
    | '/library'
    | '/login'
    | '/messages'
    | '/privacy'
    | '/privacy-policy'
    | '/pro'
    | '/refunds'
    | '/register'
    | '/saved'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/site-map'
    | '/takedown'
    | '/terms'
    | '/terms-of-service'
    | '/trust'
    | '/category/$slug'
    | '/checkout/return'
    | '/creators/$handle'
    | '/guides/$slug'
    | '/legal/$slug'
    | '/profile/$username'
    | '/profile/edit'
    | '/prompt/$slug'
    | '/prompts/$slug'
    | '/browse/'
    | '/creators/'
    | '/guides/'
    | '/.lovable/oauth/consent'
    | '/prompt/$category/$slug'
    | '/browse/$price/'
    | '/browse/$price/$model/$category'
    | '/browse/$price/$model/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DmcaRoute: typeof DmcaRoute
  EditorialStandardsRoute: typeof EditorialStandardsRoute
  GlossaryRoute: typeof GlossaryRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProRoute: typeof ProRoute
  RefundsRoute: typeof RefundsRoute
  RegisterRoute: typeof RegisterRoute
  SavedRoute: typeof SavedRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SiteMapRoute: typeof SiteMapRoute
  TakedownRoute: typeof TakedownRoute
  TermsRoute: typeof TermsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TrustRoute: typeof TrustRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CreatorsHandleRoute: typeof CreatorsHandleRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ProfileEditRoute: typeof ProfileEditRoute
  PromptSlugRoute: typeof PromptSlugRoute
  PromptsSlugRoute: typeof PromptsSlugRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  CreatorsIndexRoute: typeof CreatorsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  PromptCategorySlugRoute: typeof PromptCategorySlugRoute
  BrowsePriceIndexRoute: typeof BrowsePriceIndexRoute
  BrowsePriceModelCategoryRoute: typeof BrowsePriceModelCategoryRoute
  BrowsePriceModelIndexRoute: typeof BrowsePriceModelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-standards': {
      id: '/editorial-standards'
      path: '/editorial-standards'
      fullPath: '/editorial-standards'
      preLoaderRoute: typeof EditorialStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-map': {
      id: '/site-map'
      path: '/site-map'
      fullPath: '/site-map'
      preLoaderRoute: typeof SiteMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takedown': {
      id: '/takedown'
      path: '/takedown'
      fullPath: '/takedown'
      preLoaderRoute: typeof TakedownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/': {
      id: '/creators/'
      path: '/creators'
      fullPath: '/creators/'
      preLoaderRoute: typeof CreatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$handle': {
      id: '/creators/$handle'
      path: '/creators/$handle'
      fullPath: '/creators/$handle'
      preLoaderRoute: typeof CreatorsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/$slug': {
      id: '/prompt/$slug'
      path: '/prompt/$slug'
      fullPath: '/prompt/$slug'
      preLoaderRoute: typeof PromptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$slug': {
      id: '/prompts/$slug'
      path: '/prompts/$slug'
      fullPath: '/prompts/$slug'
      preLoaderRoute: typeof PromptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$price/': {
      id: '/browse/$price/'
      path: '/browse/$price'
      fullPath: '/browse/$price/'
      preLoaderRoute: typeof BrowsePriceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/$category/$slug': {
      id: '/prompt/$category/$slug'
      path: '/prompt/$category/$slug'
      fullPath: '/prompt/$category/$slug'
      preLoaderRoute: typeof PromptCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$price/$model/': {
      id: '/browse/$price/$model/'
      path: '/browse/$price/$model'
      fullPath: '/browse/$price/$model/'
      preLoaderRoute: typeof BrowsePriceModelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$price/$model/$category': {
      id: '/browse/$price/$model/$category'
      path: '/browse/$price/$model/$category'
      fullPath: '/browse/$price/$model/$category'
      preLoaderRoute: typeof BrowsePriceModelCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  DmcaRoute: DmcaRoute,
  EditorialStandardsRoute: EditorialStandardsRoute,
  GlossaryRoute: GlossaryRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProRoute: ProRoute,
  RefundsRoute: RefundsRoute,
  RegisterRoute: RegisterRoute,
  SavedRoute: SavedRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SiteMapRoute: SiteMapRoute,
  TakedownRoute: TakedownRoute,
  TermsRoute: TermsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TrustRoute: TrustRoute,
  CategorySlugRoute: CategorySlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CreatorsHandleRoute: CreatorsHandleRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ProfileEditRoute: ProfileEditRoute,
  PromptSlugRoute: PromptSlugRoute,
  PromptsSlugRoute: PromptsSlugRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  CreatorsIndexRoute: CreatorsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  PromptCategorySlugRoute: PromptCategorySlugRoute,
  BrowsePriceIndexRoute: BrowsePriceIndexRoute,
  BrowsePriceModelCategoryRoute: BrowsePriceModelCategoryRoute,
  BrowsePriceModelIndexRoute: BrowsePriceModelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
