// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/search-prompts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function marketplaceClient() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error("Supabase env not configured");
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var PROMPT_CARD_SELECT = "slug, title, description, model, price_pence, is_free, rating_avg, rating_count, sales_count, copies_count, featured, category:categories(slug, name), creator:profiles!prompts_creator_id_fkey(handle, display_name)";
var SITE_URL = "https://www.pasteprompts.co.uk";
function promptUrl(slug) {
  return `${SITE_URL}/prompt/${slug}`;
}
function sanitizeSearchTerm(raw) {
  return raw.replace(/[,.()%*\\"'`:]/g, " ").replace(/\s+/g, " ").trim().slice(0, 100);
}

// src/lib/mcp/tools/search-prompts.ts
var search_prompts_default = defineTool({
  name: "search_prompts",
  title: "Search prompts",
  description: "Search the PastePrompts marketplace for approved AI prompts. Filter by keyword, AI model, price band, and sort order.",
  inputSchema: {
    query: z.string().optional().describe("Keyword to match in the title or description."),
    model: z.string().optional().describe("Filter by AI model, e.g. 'gpt-4', 'midjourney', 'claude'."),
    price: z.enum(["free", "paid", "under5", "5to15", "over15"]).optional().describe("Price band filter."),
    sort: z.enum(["trending", "newest", "rated", "popular"]).optional().describe("Sort order (default: trending)."),
    category: z.string().optional().describe("Category slug to filter by."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 12).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, model, price, sort, category, limit }) => {
    const supabase = marketplaceClient();
    let q = supabase.from("prompts").select(PROMPT_CARD_SELECT).eq("status", "approved");
    if (query) {
      const term = sanitizeSearchTerm(query);
      if (term) q = q.or(`title.ilike.%${term}%,description.ilike.%${term}%`);
    }
    if (model && model !== "all") q = q.eq("model", model);
    if (price === "free") q = q.eq("is_free", true);
    if (price === "paid") q = q.eq("is_free", false);
    if (price === "under5") q = q.lt("price_pence", 500).eq("is_free", false);
    if (price === "5to15") q = q.gte("price_pence", 500).lte("price_pence", 1500);
    if (price === "over15") q = q.gt("price_pence", 1500);
    if (category) {
      const { data: cat } = await supabase.from("categories").select("id").eq("slug", category).maybeSingle();
      if (cat) q = q.eq("category_id", cat.id);
    }
    switch (sort) {
      case "newest":
        q = q.order("created_at", { ascending: false });
        break;
      case "rated":
        q = q.order("rating_avg", { ascending: false }).order("rating_count", { ascending: false });
        break;
      case "popular":
        q = q.order("sales_count", { ascending: false });
        break;
      default:
        q = q.order("trending_score", { ascending: false }).order("sales_count", { ascending: false });
    }
    q = q.limit(limit ?? 12);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = (data ?? []).map((p) => ({
      slug: p.slug,
      title: p.title,
      description: p.description,
      model: p.model,
      price: p.is_free ? "Free" : `\xA3${((p.price_pence ?? 0) / 100).toFixed(2)}`,
      rating: p.rating_avg,
      sales: p.sales_count,
      category: p.category?.name ?? null,
      creator: p.creator?.display_name ?? null,
      url: promptUrl(p.slug)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ count: results.length, results }, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/get-prompt.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var PROMPT_DETAIL_SELECT = "slug, title, description, example_output, model, price_pence, is_free, rating_avg, rating_count, sales_count, copies_count, views, featured, tags, created_at, category:categories(slug, name), creator:profiles!prompts_creator_id_fkey(handle, display_name, bio, total_sales)";
var get_prompt_default = defineTool2({
  name: "get_prompt",
  title: "Get prompt details",
  description: "Get full public details for a single PastePrompts marketplace prompt by its slug. The paid prompt body is not returned \u2014 link users to the prompt page to purchase or copy it.",
  inputSchema: {
    slug: z2.string().min(1).describe("The prompt slug, e.g. 'cinematic-portrait-midjourney'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = marketplaceClient();
    const { data, error } = await supabase.from("prompts").select(PROMPT_DETAIL_SELECT).eq("slug", slug).eq("status", "approved").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No approved prompt found for slug "${slug}".` }], isError: true };
    const p = data;
    const detail = {
      slug: p.slug,
      title: p.title,
      description: p.description,
      example_output: p.example_output,
      model: p.model,
      price: p.is_free ? "Free" : `\xA3${((p.price_pence ?? 0) / 100).toFixed(2)}`,
      rating: p.rating_avg,
      rating_count: p.rating_count,
      sales: p.sales_count,
      views: p.views,
      tags: p.tags,
      category: p.category?.name ?? null,
      creator: p.creator?.display_name ?? null,
      created_at: p.created_at,
      url: promptUrl(p.slug)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(detail, null, 2) }],
      structuredContent: detail
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all prompt categories available on the PastePrompts marketplace.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = marketplaceClient();
    const { data, error } = await supabase.from("categories").select("slug, name, description").order("sort_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const categories = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify({ count: categories.length, categories }, null, 2) }],
      structuredContent: { count: categories.length, categories }
    };
  }
});

// src/lib/mcp/tools/get-featured-prompts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_featured_prompts_default = defineTool4({
  name: "get_featured_prompts",
  title: "Get featured prompts",
  description: "Get the currently featured / trending prompts on the PastePrompts marketplace.",
  inputSchema: {
    limit: z3.number().int().min(1).max(24).optional().describe("Max results (default 8).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = marketplaceClient();
    const { data, error } = await supabase.from("prompts").select(PROMPT_CARD_SELECT).eq("status", "approved").eq("featured", true).order("trending_score", { ascending: false }).limit(limit ?? 8);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = (data ?? []).map((p) => ({
      slug: p.slug,
      title: p.title,
      description: p.description,
      model: p.model,
      price: p.is_free ? "Free" : `\xA3${((p.price_pence ?? 0) / 100).toFixed(2)}`,
      rating: p.rating_avg,
      category: p.category?.name ?? null,
      url: promptUrl(p.slug)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ count: results.length, results }, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/publish-article.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("This tool requires an authenticated connection");
  return createClient2(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function slugify(input) {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80);
}
var SITE_URL2 = "https://www.pasteprompts.co.uk";

// src/lib/mcp/tools/publish-article.ts
var blockSchema = z4.discriminatedUnion("type", [
  z4.object({ type: z4.literal("p"), text: z4.string().min(1) }),
  z4.object({ type: z4.literal("h2"), text: z4.string().min(1) }),
  z4.object({ type: z4.literal("h3"), text: z4.string().min(1) }),
  z4.object({ type: z4.literal("list"), items: z4.array(z4.string().min(1)).min(1) }),
  z4.object({ type: z4.literal("steps"), items: z4.array(z4.string().min(1)).min(1) }),
  z4.object({ type: z4.literal("quote"), text: z4.string().min(1) }),
  z4.object({ type: z4.literal("code"), label: z4.string().optional(), text: z4.string().min(1) })
]);
var publish_article_default = defineTool5({
  name: "publish_article",
  title: "Publish SEO article",
  description: "Publish a long-form SEO article to the Paste Prompts Learn hub at /guides/<slug>. Requires an admin account. Articles must be original, substantial (8+ blocks) and genuinely useful.",
  inputSchema: {
    title: z4.string().trim().min(10).max(120).describe("Article H1 / SEO title."),
    description: z4.string().trim().min(50).max(300).describe("Meta description (50-160 chars ideal)."),
    intro: z4.string().trim().min(120).describe("Opening paragraph shown under the title."),
    blocks: z4.array(blockSchema).min(6).describe("Body content blocks in reading order."),
    takeaways: z4.array(z4.string().min(5)).min(3).max(8).describe("Key takeaway bullet points."),
    slug: z4.string().trim().optional().describe("URL slug; derived from the title when omitted."),
    category: z4.string().trim().max(40).optional().describe("Topic label, e.g. 'Fundamentals'."),
    emoji: z4.string().trim().max(4).optional(),
    read_minutes: z4.number().int().min(2).max(30).optional(),
    status: z4.enum(["published", "draft"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const slug = slugify(input.slug || input.title);
    const words = [
      input.intro,
      ...input.blocks.map((b) => {
        const anyBlock = b;
        return anyBlock.text ?? (anyBlock.items ?? []).join(" ");
      })
    ].join(" ").split(/\s+/).length;
    const { data, error } = await supabase.from("articles").insert({
      slug,
      title: input.title,
      description: input.description,
      intro: input.intro,
      blocks: input.blocks,
      takeaways: input.takeaways,
      category: input.category ?? "Guides",
      emoji: input.emoji ?? "\u{1F4D8}",
      read_minutes: input.read_minutes ?? Math.max(3, Math.round(words / 200)),
      status: input.status ?? "published",
      created_by: ctx.getUserId()
    }).select("slug, status").single();
    if (error) {
      const hint = error.code === "23505" ? " (an article with this slug already exists \u2014 use update_article)" : "";
      return { content: [{ type: "text", text: `Could not publish: ${error.message}${hint}` }], isError: true };
    }
    const url = `${SITE_URL2}/guides/${data.slug}`;
    return {
      content: [{ type: "text", text: `Published "${input.title}" (${data.status}) at ${url}` }],
      structuredContent: { slug: data.slug, status: data.status, url }
    };
  }
});

// src/lib/mcp/tools/update-article.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.25.76";
var blockSchema2 = z5.discriminatedUnion("type", [
  z5.object({ type: z5.literal("p"), text: z5.string().min(1) }),
  z5.object({ type: z5.literal("h2"), text: z5.string().min(1) }),
  z5.object({ type: z5.literal("h3"), text: z5.string().min(1) }),
  z5.object({ type: z5.literal("list"), items: z5.array(z5.string().min(1)).min(1) }),
  z5.object({ type: z5.literal("steps"), items: z5.array(z5.string().min(1)).min(1) }),
  z5.object({ type: z5.literal("quote"), text: z5.string().min(1) }),
  z5.object({ type: z5.literal("code"), label: z5.string().optional(), text: z5.string().min(1) })
]);
var update_article_default = defineTool6({
  name: "update_article",
  title: "Update or unpublish article",
  description: "Edit an existing Learn-hub article by slug, or change its status to draft/published. Requires an admin account. Only the supplied fields change.",
  inputSchema: {
    slug: z5.string().trim().min(1).describe("Slug of the article to update."),
    title: z5.string().trim().min(10).max(120).optional(),
    description: z5.string().trim().min(50).max(300).optional(),
    intro: z5.string().trim().min(60).optional(),
    blocks: z5.array(blockSchema2).min(6).optional(),
    takeaways: z5.array(z5.string().min(5)).min(3).max(8).optional(),
    category: z5.string().trim().max(40).optional(),
    emoji: z5.string().trim().max(4).optional(),
    read_minutes: z5.number().int().min(2).max(30).optional(),
    status: z5.enum(["published", "draft"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ slug, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const patch = Object.fromEntries(Object.entries(fields).filter(([, v]) => v !== void 0));
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "Nothing to update." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("articles").update(patch).eq("slug", slug).select("slug, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: `No article found with slug "${slug}" (or you lack admin rights).` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Updated ${data.slug} (${data.status}) \u2014 ${SITE_URL2}/guides/${data.slug}` }],
      structuredContent: { slug: data.slug, status: data.status }
    };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_articles_default = defineTool7({
  name: "list_articles",
  title: "List Learn-hub articles",
  description: "List articles published to the Paste Prompts Learn hub, newest first. Use before publishing to avoid duplicate topics or slugs.",
  inputSchema: {
    limit: z6.number().int().min(1).max(50).optional().describe("Max articles to return (default 20)."),
    status: z6.enum(["published", "draft", "any"]).optional().describe("Filter by status (default published).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("articles").select("slug, title, category, status, published_at").order("published_at", { ascending: false }).limit(limit ?? 20);
    if ((status ?? "published") !== "any") query = query.eq("status", status ?? "published");
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = (data ?? []).map((a) => ({ ...a, url: `${SITE_URL2}/guides/${a.slug}` }));
    const text = items.length ? items.map((a) => `- ${a.title} [${a.status}] ${a.url}`).join("\n") : "No articles yet.";
    return { content: [{ type: "text", text }], structuredContent: { articles: items } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iwmljuoplkqyhdygajpi";
var mcp_default = defineMcp({
  name: "pasteprompts-mcp",
  title: "PastePrompts MCP",
  version: "0.2.0",
  instructions: "Tools for the PastePrompts AI-prompt marketplace (pasteprompts.co.uk). Read: `search_prompts` finds prompts by keyword, model or price; `get_prompt` returns full details for one slug; `list_categories` browses categories; `get_featured_prompts` returns trending picks. Prompt bodies are paid content and are never returned \u2014 share the prompt URL instead. Write (admin accounts only): `list_articles` shows existing Learn-hub articles, `publish_article` publishes a new long-form SEO article to /guides/<slug>, and `update_article` edits or unpublishes one. Articles must be original, factual and at least 800 words across the `blocks` array; check `list_articles` first to avoid duplicate topics.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_prompts_default,
    get_prompt_default,
    list_categories_default,
    get_featured_prompts_default,
    list_articles_default,
    publish_article_default,
    update_article_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
